name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  #  unit-test:
  #    needs: [ lint ]
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v2
  #
  #      - name: Run tests
  #        run: ./gradlew test
  #
  #      - name: Upload test report
  #        uses: actions/upload-artifact@v2
  #        with:
  #          name: unit_test_report
  #          path: app/build/reports/tests/testDebugUnitTest/
  #
  #  static-code-analysis:
  #    needs: [ unit-test ]
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout the code
  #        uses: actions/checkout@v2
  #
  #      - name: set up JDK 11
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 11
  #
  #      - name: SonarCloud Scan
  #        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN_NOTE_APP }}
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version-increment:
    #    needs: [ static-code-analysis ]
    runs-on: ubuntu-latest
    steps:
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Update patch version
        run: ./gradlew bumpPatchVersion

      - name: Update minor version
        run: ./gradlew bumpMinorVersion

      - name: Commit the changes
        run: |
          git config --global user.name 'Ali Göktaş'
          git config --global user.email 'eng.ali.goktas@gmail.com'
          git commit -am "Updated version"
          git push

  package:
    needs: [ version-increment ]
    name: generate apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: note-app.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload APK to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: aligoktas/Note-App
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: app/build/outputs/apk/release/app-release.apk
          notifyTesters: true
          debug: false
